with tope as(select current_date as fecha),cs AS(SELECT fecha FROM corte_modelo WHERE id=1),seg AS(SELECT articulo_id,SUM(bultos_segunda)AS total FROM reprocesos,cs,tope WHERE anulado_el IS NULL AND fecha_operacion<=tope.fecha AND(fecha_operacion>cs.fecha OR(tipo='inicial' AND fecha_operacion>=cs.fecha))GROUP BY articulo_id),sre AS(SELECT articulo_id,SUM(bultos_segunda)AS total FROM movimientos_stock,cs,tope WHERE anulado_el IS NULL AND destino_rechazo IN('segunda','reproceso')AND fecha_operacion>cs.fecha AND fecha_operacion<=tope.fecha GROUP BY articulo_id),spa AS(SELECT articulo_id,SUM(bultos_segunda)AS total FROM movimientos_stock,cs,tope WHERE anulado_el IS NULL AND tipo='pase_a_segunda' AND fecha_operacion>cs.fecha AND fecha_operacion<=tope.fecha GROUP BY articulo_id),rem AS(SELECT articulo_id,SUM(bultos)AS total FROM remitos_segunda,cs,tope WHERE anulado_el IS NULL AND fecha_operacion>cs.fecha AND fecha_operacion<=tope.fecha GROUP BY articulo_id),vig AS(SELECT DISTINCT ON(cliente_id,fecha_operacion)id FROM pedidos WHERE anulado_el IS NULL ORDER BY cliente_id,fecha_operacion,creado_en DESC),env AS(SELECT r.articulo_id,SUM(r.bultos_de_segunda)AS total FROM pedidos_renglones r JOIN vig v ON v.id=r.pedido_id,cs,tope WHERE r.bultos_de_segunda IS NOT NULL AND r.armado_el IS NOT NULL AND r.anulado_el IS NULL AND(r.armado_el AT TIME ZONE 'America/Argentina/Buenos_Aires')::date>cs.fecha AND(r.armado_el AT TIME ZONE 'America/Argentina/Buenos_Aires')::date<=tope.fecha GROUP BY r.articulo_id),aju AS(SELECT articulo_id,SUM(bultos)AS total FROM ajustes_segunda,cs,tope WHERE anulado_el IS NULL AND fecha_operacion>=cs.fecha AND fecha_operacion<=tope.fecha GROUP BY articulo_id)
,q as(select a.nombre,coalesce(g.total,0)producida,coalesce(r.total,0)rechazos,coalesce(p.total,0)pases,
coalesce(m.total,0)remitida,coalesce(e.total,0)enviada,coalesce(j.total,0)ajustes
from articulos a left join seg g on g.articulo_id=a.id left join sre r on r.articulo_id=a.id
left join spa p on p.articulo_id=a.id left join rem m on m.articulo_id=a.id
left join env e on e.articulo_id=a.id left join aju j on j.articulo_id=a.id
where coalesce(g.articulo_id,r.articulo_id,p.articulo_id,m.articulo_id,e.articulo_id,j.articulo_id)is not null)
select nombre,producida,rechazos,pases,remitida,enviada,ajustes,
producida+rechazos+pases-remitida-enviada+ajustes as pool,(select fecha from cs)corte
from q order by pool,nombre;
-- Solo lectura. El WITH es _SQL_POOL_SEGUNDA con nombres cortos.
