with tope as (select current_date as fecha) , corte_seg AS (SELECT fecha FROM corte_modelo WHERE id = 1) , segunda AS ( SELECT articulo_id, SUM(bultos_segunda) AS total FROM reprocesos, corte_seg, tope WHERE anulado_el IS NULL AND fecha_operacion <= tope.fecha AND (fecha_operacion > corte_seg.fecha OR (tipo = 'inicial' AND fecha_operacion >= corte_seg.fecha)) GROUP BY articulo_id ), segunda_rechazo AS ( SELECT articulo_id, SUM(bultos_segunda) AS total FROM movimientos_stock, corte_seg, tope WHERE anulado_el IS NULL AND destino_rechazo IN ('segunda', 'reproceso') AND fecha_operacion > corte_seg.fecha AND fecha_operacion <= tope.fecha GROUP BY articulo_id ), segunda_pase AS ( SELECT articulo_id, SUM(bultos_segunda) AS total FROM movimientos_stock, corte_seg, tope WHERE anulado_el IS NULL AND tipo = 'pase_a_segunda' AND fecha_operacion > corte_seg.fecha AND fecha_operacion <= tope.fecha GROUP BY articulo_id ), remitida AS ( SELECT articulo_id, SUM(bultos) AS total FROM remitos_segunda, corte_seg, tope WHERE anulado_el IS NULL AND fecha_operacion > corte_seg.fecha AND fecha_operacion <= tope.fecha GROUP BY articulo_id ), vigentes_seg AS ( SELECT DISTINCT ON (cliente_id, fecha_operacion) id FROM pedidos WHERE anulado_el IS NULL ORDER BY cliente_id, fecha_operacion, creado_en DESC ), enviada AS ( SELECT r.articulo_id, SUM(r.bultos_de_segunda) AS total FROM pedidos_renglones r JOIN vigentes_seg v ON v.id = r.pedido_id, corte_seg, tope WHERE r.bultos_de_segunda IS NOT NULL AND r.armado_el IS NOT NULL AND r.anulado_el IS NULL AND (r.armado_el AT TIME ZONE 'America/Argentina/Buenos_Aires')::date > corte_seg.fecha AND (r.armado_el AT TIME ZONE 'America/Argentina/Buenos_Aires')::date <= tope.fecha GROUP BY r.articulo_id )
, q as (select a.nombre, coalesce(sg.total,0) producida, coalesce(sr.total,0) rechazos,
coalesce(sp.total,0) pases, coalesce(rm.total,0) remitida, coalesce(en.total,0) enviada
from articulos a left join segunda sg on sg.articulo_id=a.id
left join segunda_rechazo sr on sr.articulo_id=a.id left join segunda_pase sp on sp.articulo_id=a.id
left join remitida rm on rm.articulo_id=a.id left join enviada en on en.articulo_id=a.id
where coalesce(sg.articulo_id,sr.articulo_id,sp.articulo_id,rm.articulo_id,en.articulo_id) is not null)
select nombre, producida, rechazos, pases, remitida, enviada,
producida+rechazos+pases-remitida-enviada as pool, (select fecha from corte_seg) corte
from q order by pool, nombre;
-- Solo lectura. El WITH es _SQL_POOL_SEGUNDA.
